sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
before_script: cp api/config.example.js api/config.js
script: npm run test
